version: "3.9"
services:
  gitea:
    dns:
      - 10.0.4.200
      - 10.0.4.201
    build:
      args:
        ALPINE_VERSION: "latest"
        CONTAINER_VERSION: "1.21.3"
        GITEA_VERSION: "1.21.3"
      context: .
      dockerfile: container.build
      no_cache: true  
      tags:
        - "gitea:build"
        - "gautada/gitea:build"
        - "gautada/gitea:latest"
    image: "gautada/gitea:latest"
    hostname: gitea
    container_name: gitea
    ports:
      - "8080:8080"
    volumes:
      - "Container:/mnt/volumes/container"
      - "Backup:/mnt/volumes/backup"
      - "Configmaps:/mnt/volumes/configmaps"
      - "Secrets:/mnt/volumes/secrets"


volumes:
  Container:
    external: true
    name: "Container"

  Backup:
    external: true
    name: "Backup"

  Configmaps:
    external: true
    name: "Configmaps"
    
  Secrets:
    external: true
    name: "Secrets"
    
