kind: pipeline
type: exec
name: Container Build - Gitea



platform:
  os: linux
  arch: arm64

steps:
- name: build
  environment:
    ALPINE_VERSION: "latest"
    GITEA_VERSION: 1.19.0
  commands:
  - podman build --build-arg ALPINE_VERSION=$ALPINE_VERSION --build-arg GITEA_VERSION=$GITEA_VERSION --file Containerfile --format docker --label revision="$(git rev-parse HEAD)" --label version="$(date +%Y.%m.%d)" --no-cache --tag gitea:drone .


- name: publish
  environment:
    CONTAINER_NAME: "gitea"
    CONTAINER_VERSION: 1.19.0
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
  commands:
   - podman tag $CONTAINER_NAME:drone docker.io/$DOCKERIO_USERNAME/$CONTAINER_NAME:$CONTAINER_VERSION
   - podman tag $CONTAINER_NAME:drone docker.io/$DOCKERIO_USERNAME/$CONTAINER_NAME:latest
   - podman login --username=$DOCKERIO_USERNAME --password=$DOCKERIO_PASSWORD docker.io
   - podman push docker.io/$DOCKERIO_USERNAME/$CONTAINER_NAME:$CONTAINER_VERSION
   - podman push docker.io/$DOCKERIO_USERNAME/$CONTAINER_NAME:latest
   

trigger:
  branch:
  - main
  
